language: smalltalk

sudo: required
dist: bionic

os:
  - linux

smalltalk:
  - Pharo64-8.0
  - Pharo64-7.0
  - Pharo32-6.1

env:
  - MONGODB=4.2
  - MONGODB=4.0
  - MONGODB=3.6
  - MONGODB=3.4

matrix:
  # Finish the build as soon as one job fails
  fast_finish: true

before_install:
- bash .install_mongodb_on_travis.sh
- sleep 15  # https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections
- mongo --eval 'db.version();'

before_script:
  - "mongo test --eval 'db.createUser({ \"user\": \"pharounittest\", \"pwd\": \"test\", roles: [] });'"
  - export baseRepositoryPath=$SMALLTALK_CI_BUILD/replicatest/
  - export replicaSetName=db
  - ./scripts/rs-setup.sh

# bob-bench xUnit file analysis
after_script:
  - pip install --user benchupload && benchupload
